In [1]:
import requests        # for making http requests to binance
import json            # for parsing what binance sends back to us
import pandas as pd    # for storing and manipulating the data we get back
import numpy as np     # numerical python, i usually need this somewhere 
                       # and so i import by habit nowadays

import matplotlib.pyplot as plt # for charts and such
    
import datetime as dt  # for dealing with times

In [2]:
root_url = 'https://api.binance.com/api/v1/klines'

In [69]:
def get_bars(symbol, interval = '1h', limit=500, starttime='', endtime=''):
    url = root_url + '?symbol=' + symbol + '&interval=' + interval + '&limit=' + str(limit)
    if starttime:
        url = url + '&startTime=' + str(starttime)
    if endtime:
        url = url + '&endTime=' + str(endtime)
    data = json.loads(requests.get(url).text)
    try:
        df = pd.DataFrame(data)
    except:
        raise ValueError(data)
    df.columns = ['open_time',
                  'o', 'h', 'l', 'c', 'v',
                  'close_time', 'qav', 'num_trades',
                  'taker_base_vol', 'taker_quote_vol', 'ignore']
    df.index = [dt.datetime.fromtimestamp(x/1000.0) for x in df.close_time]
    return df

In [116]:
df = get_bars("BNBBTC", interval='15m', limit=1000, starttime=1500004800000, endtime='')

In [117]:
len(df)

1000

In [118]:
df.head()

,open_time,o,h,l,c,v,close_time,qav,num_trades,taker_base_vol,taker_quote_vol,ignore
2017-07-14 13:29:59.999,1500005700000,0.00004086,0.00004898,0.00004000,0.00004747,1259082.00000000,1500006599999,56.06023368,305,943579.00000000,41.91450043,84713908.44046950
2017-07-14 13:44:59.999,1500006600000,0.00004747,0.00005480,0.00004747,0.00005348,1468616.00000000,1500007499999,76.15190292,295,1173502.00000000,60.49395309,85284586.80346950
2017-07-14 13:59:59.999,1500007500000,0.00005300,0.00005348,0.00004746,0.00004955,977907.00000000,1500008399999,49.83045683,218,372278.00000000,19.65486654,86413164.78446950
2017-07-14 14:14:59.999,1500008400000,0.00004946,0.00004946,0.00004480,0.00004491,625622.00000000,1500009299999,29.46253842,153,113307.00000000,5.45375234,86369375.53446950
2017-07-14 14:29:59.999,1500009300000,0.00004491,0.00004520,0.00003900,0.00004395,619113.00000000,1500010199999,25.27678474,123,177194.00000000,7.30468249,86339365.25446950

In [100]:
df.tail()

,open_time,o,h,l,c,v,close_time,qav,num_trades,taker_base_vol,taker_quote_vol,ignore
2017-07-24 21:59:59.999,1500900300000,0.00004201,0.00004210,0.00004200,0.00004209,7947.00000000,1500901199999,0.33422454,17,1915.00000000,0.08061958,100045602.28789950
2017-07-24 22:14:59.999,1500901200000,0.00004209,0.00004224,0.00004200,0.00004218,22332.00000000,1500902099999,0.94069304,21,20998.00000000,0.88465282,100040614.28789950
2017-07-24 22:29:59.999,1500902100000,0.00004216,0.00004218,0.00004208,0.00004211,7952.00000000,1500902999999,0.33503502,22,4852.00000000,0.20446648,100048799.28789950
2017-07-24 22:44:59.999,1500903000000,0.00004216,0.00004225,0.00004214,0.00004222,36773.00000000,1500903899999,1.55194888,30,31338.00000000,1.32278706,100048799.28789950
2017-07-24 22:59:59.999,1500903900000,0.00004228,0.00004230,0.00004221,0.00004229,17608.00000000,1500904799999,0.74418614,23,10034.00000000,0.42421623,100048799.28789950

In [129]:
22332.00000000 * 0.00004209

0.93995388

In [74]:
dt.datetime.fromtimestamp(1500000000000/1000).strftime("%A, %B %d, %Y %I:%M:%S")

'Friday, July 14, 2017 11:40:00'

In [112]:
repr(df['open_time'][-1])

'1500903900000'

In [131]:
dfs = []
starttime = 1500004800000

l = 1000
i = 0
while l == 1000:
# for _ in range(5):
    df = get_bars("BNBBTC", interval='15m', limit=1000, starttime=starttime, endtime='')
    dfs.append(df)
    l = len(df)
    starttime = int(df['open_time'][-1]) + 1
    i += 1
    print(i, end='\r')

In [124]:
len(dfs[0])

1000

In [125]:
len(dfs[1])

1000

In [127]:
len(pd.concat(dfs))

5000

In [133]:
len(dfs[-1])

812

In [134]:
huge_df = pd.concat(dfs)

In [135]:
len(huge_df)

69812

In [138]:
huge_df.to_hdf('binance_data.h5', 'STW')

In [139]:
pd.read_hdf('binance_data.h5', 'STW')

,open_time,o,h,l,c,v,close_time,qav,num_trades,taker_base_vol,taker_quote_vol,ignore
2017-07-14 13:14:59.999,1500004800000,0.00005000,0.00005300,0.00001000,0.00004000,3148043.00000000,1500005699999,130.30196612,451,2669352.00000000,111.18404497,84396652.45546950
2017-07-14 13:29:59.999,1500005700000,0.00004086,0.00004898,0.00004000,0.00004747,1259082.00000000,1500006599999,56.06023368,305,943579.00000000,41.91450043,84713908.44046950
2017-07-14 13:44:59.999,1500006600000,0.00004747,0.00005480,0.00004747,0.00005348,1468616.00000000,1500007499999,76.15190292,295,1173502.00000000,60.49395309,85284586.80346950
2017-07-14 13:59:59.999,1500007500000,0.00005300,0.00005348,0.00004746,0.00004955,977907.00000000,1500008399999,49.83045683,218,372278.00000000,19.65486654,86413164.78446950
2017-07-14 14:14:59.999,1500008400000,0.00004946,0.00004946,0.00004480,0.00004491,625622.00000000,1500009299999,29.46253842,153,113307.00000000,5.45375234,86369375.53446950
2017-07-14 14:29:59.999,1500009300000,0.00004491,0.00004520,0.00003900,0.00004395,619113.00000000,1500010199999,25.27678474,123,177194.00000000,7.30468249,86339365.25446950
2017-07-14 14:44:59.999,1500010200000,0.00004395,0.00004529,0.00004203,0.00004529,362398.00000000,1500011099999,15.91306745,83,274128.00000000,12.14350520,86352187.88246950
2017-07-14 14:59:59.999,1500011100000,0.00004597,0.00004597,0.00004262,0.00004429,127665.00000000,1500011999999,5.56272458,51,56321.00000000,2.50087845,86384888.21946950
2017-07-14 15:14:59.999,1500012000000,0.00004429,0.00004890,0.00004361,0.00004466,230946.00000000,1500012899999,10.41000060,69,199485.00000000,9.02287175,86429462.48746950
2017-07-14 15:29:59.999,1500012900000,0.00004848,0.00004848,0.00004550,0.00004829,281743.00000000,1500013799999,13.57496782,184,259136.00000000,12.49651605,86424644.48746950
2017-07-14 15:44:59.999,1500013800000,0.00004820,0.00004844,0.00004621,0.00004818,321126.00000000,1500014699999,15.39935323,71,284277.00000000,13.66339766,86438035.38746950
2017-07-14 15:59:59.999,1500014700000,0.00004794,0.00004800,0.00004710,0.00004800,164846.00000000,1500015599999,7.89959261,45,117735.00000000,5.65022391,86462804.85546950
2017-07-14 16:14:59.999,1500015600000,0.00004799,0.00004841,0.00004709,0.00004752,175235.00000000,1500016499999,8.40652946,47,103992.00000000,4.99197019,86474403.88346950
2017-07-14 16:29:59.999,1500016500000,0.00004798,0.00004840,0.00004780,0.00004815,89586.00000000,1500017399999,4.30373259,20,88424.00000000,4.24818899,86489154.28646950
2017-07-14 16:44:59.999,1500017400000,0.00004814,0.00004814,0.00004700,0.00004708,108953.00000000,1500018299999,5.19968631,37,47336.00000000,2.26628672,86502341.59746950
2017-07-14 16:59:59.999,1500018300000,0.00004797,0.00004797,0.00004702,0.00004780,163674.00000000,1500019199999,7.75262908,35,44389.00000000,2.11712981,87066028.63346950
2017-07-14 17:14:59.999,1500019200000,0.00004780,0.00004790,0.00004700,0.00004700,39605.00000000,1500020099999,1.89126869,23,28605.00000000,1.36962415,87038468.73346950
2017-07-14 17:29:59.999,1500020100000,0.00004780,0.00004780,0.00004600,0.00004600,68722.00000000,1500020999999,3.17655987,21,1059.00000000,0.04901400,87038368.73346950
2017-07-14 17:44:59.999,1500021000000,0.00004522,0.00004580,0.00004367,0.00004370,65577.00000000,1500021899999,2.91548245,34,4928.00000000,0.22102510,87049168.63346950
2017-07-14 17:59:59.999,1500021900000,0.00004375,0.00004580,0.00004331,0.00004410,75996.00000000,1500022799999,3.42647653,34,59638.00000000,2.71040901,87057390.66646950
2017-07-14 18:14:59.999,1500022800000,0.00004411,0.00004600,0.00004411,0.00004500,50092.00000000,1500023699999,2.29346724,20,43784.00000000,2.00817268,87105693.65246950
2017-07-14 18:29:59.999,1500023700000,0.00004414,0.00004678,0.00004414,0.00004677,48817.00000000,1500024599999,2.23948506,12,32799.00000000,1.53229136,87105693.65246950
2017-07-14 18:44:59.999,1500024600000,0.00004676,0.00004676,0.00004674,0.00004674,3015.00000000,1500025499999,0.14096190,4,3015.00000000,0.14096190,87105112.73046950
2017-07-14 18:59:59.999,1500025500000,0.00004515,0.00004515,0.00004282,0.00004282,81947.00000000,1500026399999,3.63553722,21,23000.00000000,1.03845000,86903512.73046950
2017-07-14 19:14:59.999,1500026400000,0.00004282,0.00004500,0.00004215,0.00004500,36889.00000000,1500027299999,1.59354943,14,13778.00000000,0.61005378,86916548.31747835
2017-07-14 19:29:59.999,1500027300000,0.00004239,0.00004490,0.00004236,0.00004490,54587.00000000,1500028199999,2.43575531,17,31088.00000000,1.39417671,87118148.31747835
2017-07-14 19:44:59.999,1500028200000,0.00004490,0.00004490,0.00004265,0.00004479,81339.00000000,1500029099999,3.62859233,15,3865.00000000,0.16728199,87111986.76747835
2017-07-14 19:59:59.999,1500029100000,0.00004350,0.00004490,0.00004350,0.00004490,30024.00000000,1500029999999,1.34454280,8,29999.00000000,1.34345530,87114477.76747835
2017-07-14 20:14:59.999,1500030000000,0.00004490,0.00004650,0.00004490,0.00004650,38331.00000000,1500030899999,1.74545790,13,38331.00000000,1.74545790,87123185.76747835
2017-07-14 20:29:59.999,1500030900000,0.00004650,0.00004800,0.00004650,0.00004800,290025.00000000,1500031799999,13.86301718,50,290000.00000000,13.86182068,87110485.76747835
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-07-15 05:14:59.999,1563134400000,0.00278510,0.00279100,0.00277860,0.00278770,20429.19000000,1563135299999,56.89098634,1593,10436.60000000,29.06325934,0
2019-07-15 05:29:59.999,1563135300000,0.00278720,0.00279370,0.00277860,0.00278600,18503.12000000,1563136199999,51.57003528,1566,9821.93000000,27.37429004,0
2019-07-15 05:44:59.999,1563136200000,0.00278690,0.00279080,0.00277520,0.00277800,15936.21000000,1563137099999,44.36009131,1405,7261.84000000,20.21743869,0
2019-07-15 05:59:59.999,1563137100000,0.00277770,0.00277770,0.00276000,0.00276900,33350.20000000,1563137999999,92.28091164,2588,12587.66000000,34.83127945,0
2019-07-15 06:14:59.999,1563138000000,0.00276900,0.00276960,0.00275510,0.00276750,20633.08000000,1563138899999,56.99941046,1814,9816.89000000,27.12149850,0
2019-07-15 06:29:59.999,1563138900000,0.00276750,0.00277840,0.00276190,0.00277550,10935.57000000,1563139799999,30.29473147,1174,5556.77000000,15.39039964,0
2019-07-15 06:44:59.999,1563139800000,0.00277550,0.00278000,0.00276420,0.00276820,12314.92000000,1563140699999,34.13908683,1147,5791.15000000,16.05313920,0
2019-07-15 06:59:59.999,1563140700000,0.00276790,0.00277810,0.00276790,0.00277630,12384.00000000,1563141599999,34.34602843,1296,5959.32000000,16.52719687,0
2019-07-15 07:14:59.999,1563141600000,0.00277650,0.00278230,0.00276940,0.00277460,17816.00000000,1563142499999,49.46887261,1444,9168.92000000,25.45966988,0
2019-07-15 07:29:59.999,1563142500000,0.00277160,0.00278100,0.00277010,0.00277610,12057.90000000,1563143399999,33.45861800,1142,5948.57000000,16.50453837,0
2019-07-15 07:44:59.999,1563143400000,0.00277720,0.00279040,0.00277430,0.00278330,22306.37000000,1563144299999,62.04752016,1847,12788.08000000,35.57048000,0
2019-07-15 07:59:59.999,1563144300000,0.00278380,0.00279770,0.00278270,0.00279540,15990.12000000,1563145199999,44.62600155,1438,8221.65000000,22.94511749,0
2019-07-15 08:14:59.999,1563145200000,0.00279520,0.00282000,0.00279250,0.00280290,53421.34000000,1563146099999,150.03048345,3829,33356.67000000,93.71007731,0
2019-07-15 08:29:59.999,1563146100000,0.00280450,0.00281570,0.00280310,0.00280750,23034.09000000,1563146999999,64.71345010,1776,10826.03000000,30.41327267,0
2019-07-15 08:44:59.999,1563147000000,0.00280790,0.00282000,0.00280180,0.00281550,25998.24000000,1563147899999,73.07031927,2024,13208.48000000,37.12744166,0
2019-07-15 08:59:59.999,1563147900000,0.00281660,0.00281670,0.00278000,0.00280420,79479.36000000,1563148799999,222.35893995,6732,41998.90000000,117.46680019,0
2019-07-15 09:14:59.999,1563148800000,0.00280420,0.00281500,0.00279200,0.00279880,65674.11000000,1563149699999,183.98209880,4563,38660.03000000,108.31772274,0
2019-07-15 09:29:59.999,1563149700000,0.00279880,0.00280140,0.00270000,0.00271380,134677.07000000,1563150599999,370.27713955,11380,46312.09000000,127.42271943,0
2019-07-15 09:44:59.999,1563150600000,0.00271130,0.00271790,0.00265610,0.00269490,127038.28000000,1563151499999,341.42691864,10538,54341.02000000,146.08181701,0
2019-07-15 09:59:59.999,1563151500000,0.00269350,0.00272400,0.00268500,0.00268900,99229.74000000,1563152399999,268.14320435,7884,47874.55000000,129.45299451,0
2019-07-15 10:14:59.999,1563152400000,0.00268950,0.00270260,0.00267770,0.00269480,56668.02000000,1563153299999,152.39462345,4980,28628.21000000,76.99902773,0
2019-07-15 10:29:59.999,1563153300000,0.00269600,0.00272000,0.00269570,0.00270910,36103.28000000,1563154199999,97.81656680,3636,19271.71000000,52.22249906,0
2019-07-15 10:44:59.999,1563154200000,0.00271050,0.00271480,0.00266180,0.00268840,56201.64000000,1563155099999,150.96601407,4611,22636.53000000,60.84703956,0
2019-07-15 10:59:59.999,1563155100000,0.00268870,0.00269210,0.00266200,0.00267330,19100.21000000,1563155999999,51.12250098,2083,10090.39000000,26.99645481,0
2019-07-15 11:14:59.999,1563156000000,0.00267300,0.00268770,0.00266840,0.00268010,21912.81000000,1563156899999,58.71781411,1979,12311.98000000,32.99273283,0
2019-07-15 11:29:59.999,1563156900000,0.00267990,0.00268610,0.00266060,0.00268370,48933.26000000,1563157799999,130.85882053,3733,27105.50000000,72.49020280,0
2019-07-15 11:44:59.999,1563157800000,0.00268230,0.00268900,0.00266160,0.00267460,50759.22000000,1563158699999,135.73850648,3605,26047.71000000,69.65477579,0
2019-07-15 11:59:59.999,1563158700000,0.00267480,0.00268800,0.00267020,0.00268780,36719.99000000,1563159599999,98.36012389,2446,21585.57000000,57.82913399,0
2019-07-15 12:14:59.999,1563159600000,0.00268770,0.00276220,0.00268410,0.00276100,68425.70000000,1563160499999,186.03515155,5119,42480.58000000,115.42749667,0
2019-07-15 12:29:59.999,1563160500000,0.00275920,0.00276500,0.00274140,0.00275000,51555.03000000,1563161399999,142.05796572,3217,20426.33000000,56.30924716,0

In [141]:
pd.read_hdf('SGXTWsample.h5', 'STW')

,serial_number,datetime,Comm,Price,Volume,Ask_price,Bid_price,Ask_deal_vol,Bid_deal_vol,Bid/Ask_deal,Updown,Updown_Cum
0,0,2013-04-09 10:45:03,TW,277.3,9,277.3,277.3,9.0,9.0,0.0,0.0,0.0
1,1,2013-04-09 10:45:03,TW,277.3,8,277.3,277.3,8.0,8.0,0.0,0.0,0.0
2,2,2013-04-09 10:45:03,TW,277.3,4,277.3,277.3,4.0,4.0,0.0,0.0,0.0
3,3,2013-04-09 10:45:03,TW,277.3,7,277.3,277.3,7.0,7.0,0.0,0.0,0.0
4,4,2013-04-09 10:45:03,TW,277.3,4,277.3,277.3,4.0,4.0,0.0,0.0,0.0
5,5,2013-04-09 10:45:03,TW,277.3,4,277.3,277.3,4.0,4.0,0.0,0.0,0.0
6,6,2013-04-09 10:45:03,TW,277.3,1,277.3,277.3,1.0,1.0,0.0,0.0,0.0
7,7,2013-04-09 10:45:03,TW,277.3,20,277.3,277.3,20.0,20.0,0.0,0.0,0.0
8,8,2013-04-09 10:45:03,TW,277.3,3,277.3,277.3,3.0,3.0,0.0,0.0,0.0
9,9,2013-04-09 10:45:03,TW,277.3,6,277.3,277.3,6.0,6.0,0.0,0.0,0.0
10,10,2013-04-09 10:45:03,TW,277.3,2,277.3,277.3,2.0,2.0,0.0,0.0,0.0
11,11,2013-04-09 10:45:03,TW,277.3,1,277.3,277.3,1.0,1.0,0.0,0.0,0.0
12,12,2013-04-09 10:45:03,TW,277.3,1,277.3,277.3,1.0,1.0,0.0,0.0,0.0
13,13,2013-04-09 10:45:03,TW,277.3,3,277.3,277.3,3.0,3.0,0.0,0.0,0.0
14,14,2013-04-09 10:45:03,TW,277.3,8,277.3,277.3,8.0,8.0,0.0,0.0,0.0
15,15,2013-04-09 10:45:03,TW,277.3,18,277.3,277.3,18.0,18.0,0.0,0.0,0.0
16,16,2013-04-09 10:45:03,TW,277.3,1,277.3,277.3,1.0,1.0,0.0,0.0,0.0
17,17,2013-04-09 10:45:03,TW,277.3,1,277.3,277.3,1.0,1.0,0.0,0.0,0.0
18,18,2013-04-09 10:45:03,TW,277.3,1,277.3,277.3,1.0,1.0,0.0,0.0,0.0
19,19,2013-04-09 10:45:03,TW,277.3,5,277.3,277.3,5.0,5.0,0.0,0.0,0.0
20,20,2013-04-09 10:45:03,TW,277.3,2,277.3,277.3,2.0,2.0,0.0,0.0,0.0
21,21,2013-04-09 10:45:03,TW,277.3,2,277.3,277.3,2.0,2.0,0.0,0.0,0.0
22,22,2013-04-09 10:45:03,TW,277.3,4,277.3,277.3,4.0,4.0,0.0,0.0,0.0
23,23,2013-04-09 10:45:03,TW,277.3,17,277.3,277.3,17.0,17.0,0.0,0.0,0.0
24,24,2013-04-09 10:45:03,TW,277.3,1,277.3,277.3,1.0,1.0,0.0,0.0,0.0
25,25,2013-04-09 10:45:03,TW,277.3,3,277.3,277.3,3.0,3.0,0.0,0.0,0.0
26,26,2013-04-09 10:45:03,TW,277.3,5,277.3,277.3,5.0,5.0,0.0,0.0,0.0
27,27,2013-04-09 10:45:03,TW,277.3,2,277.3,277.3,2.0,2.0,0.0,0.0,0.0
28,28,2013-04-09 10:45:03,TW,277.3,25,277.3,277.3,25.0,25.0,0.0,0.0,0.0
29,29,2013-04-09 10:45:03,TW,277.3,5,277.3,277.3,5.0,5.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
113029,25587,2013-04-20 01:55:54,TW,287.8,1,287.9,287.8,0.0,1.0,4498.0,0.1,10.9
113030,25588,2013-04-20 01:57:35,TW,287.8,1,287.9,287.8,0.0,1.0,4499.0,0.0,10.9
113031,25589,2013-04-20 01:57:44,TW,287.9,1,287.9,287.8,1.0,0.0,4498.0,0.1,11.0
113032,25590,2013-04-20 01:57:50,TW,287.8,1,287.9,287.8,0.0,1.0,4499.0,-0.1,10.9
113033,25591,2013-04-20 01:59:00,TW,287.8,1,287.8,287.7,1.0,0.0,4498.0,0.0,10.9
113034,25592,2013-04-20 01:59:00,TW,287.8,5,287.8,287.7,5.0,0.0,4493.0,0.0,10.9
113035,25593,2013-04-20 01:59:00,TW,287.8,1,287.8,287.7,1.0,0.0,4492.0,0.0,10.9
113036,25594,2013-04-20 01:59:00,TW,287.8,1,287.8,287.7,1.0,0.0,4491.0,0.0,10.9
113037,25595,2013-04-20 01:59:00,TW,287.8,1,287.8,287.7,1.0,0.0,4490.0,0.0,10.9
113038,25596,2013-04-20 01:59:00,TW,287.8,1,287.8,287.7,1.0,0.0,4489.0,0.0,10.9
113039,25597,2013-04-20 01:59:00,TW,287.8,4,287.8,287.7,4.0,0.0,4485.0,0.0,10.9
113040,25598,2013-04-20 01:59:00,TW,287.8,1,287.8,287.7,1.0,0.0,4484.0,0.0,10.9
113041,25599,2013-04-20 01:59:00,TW,287.8,4,287.8,287.7,4.0,0.0,4480.0,0.0,10.9
113042,25600,2013-04-20 01:59:00,TW,287.8,4,287.8,287.7,4.0,0.0,4476.0,0.0,10.9
113043,25601,2013-04-20 01:59:00,TW,287.8,6,287.8,287.7,6.0,0.0,4470.0,0.0,10.9
113044,25602,2013-04-20 01:59:02,TW,287.7,1,287.8,287.7,0.0,1.0,4471.0,-0.1,10.8
113045,25603,2013-04-20 01:59:13,TW,287.7,1,287.8,287.7,0.0,1.0,4472.0,0.0,10.8
113046,25604,2013-04-20 01:59:27,TW,287.7,1,287.8,287.7,0.0,1.0,4473.0,0.0,10.8
113047,25605,2013-04-20 01:59:29,TW,287.7,1,287.8,287.7,0.0,1.0,4474.0,0.0,10.8
113048,25606,2013-04-20 01:59:37,TW,287.8,5,287.8,287.7,5.0,0.0,4469.0,0.1,10.9
113049,25607,2013-04-20 01:59:37,TW,287.8,2,287.8,287.7,2.0,0.0,4467.0,0.0,10.9
113050,25608,2013-04-20 01:59:37,TW,287.8,1,287.8,287.7,1.0,0.0,4466.0,0.0,10.9
113051,25609,2013-04-20 01:59:37,TW,287.8,1,287.8,287.7,1.0,0.0,4465.0,0.0,10.9
113052,25610,2013-04-20 01:59:37,TW,287.8,1,287.8,287.7,1.0,0.0,4464.0,0.0,10.9
113053,25611,2013-04-20 01:59:38,TW,287.8,1,287.8,287.7,1.0,0.0,4463.0,0.0,10.9
113054,25612,2013-04-20 01:59:38,TW,287.7,1,287.9,287.7,0.0,1.0,4464.0,-0.1,10.8
113055,25613,2013-04-20 01:59:48,TW,287.8,2,287.9,287.7,0.0,0.0,4464.0,0.1,10.9
113056,25614,2013-04-20 01:59:49,TW,287.8,1,287.9,287.8,0.0,1.0,4465.0,0.0,10.9
113057,25615,2013-04-20 01:59:49,TW,287.8,1,287.9,287.8,0.0,1.0,4466.0,0.0,10.9
113058,25616,2013-04-20 01:59:57,TW,287.8,2,287.9,287.8,0.0,2.0,4468.0,0.0,10.9